#!/bin/busybox sh

/bin/busybox --install -s /bin

mkdir -p /dev
mount -t devtmpfs devtmpfs /dev
mkdir -p /proc
mount -t proc proc /proc
mkdir -p /sys
mount -t sysfs sysfs /sys

exec setsid cttyhack sh
