name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.toolchain }}
        components: rustfmt, clippy
    - run: cargo build --verbose
    - run: cargo build --all-features --verbose
    - run: cargo test --verbose
    - run: cargo fmt --all -- --check
    - run: cargo clippy --all-targets -- -D warnings
    - run: cargo clippy --all-targets --all-features -- -D warnings
